#!/bin/sh
# run the packaged JAR

if [ ! -f ./target/sorting-visualizer.jar ]; then
    echo "Jar not found, please build first (./build) or run mvn package."
    exit 1
fi

java -jar ./target/sorting-visualizer.jar
