#!/bin/sh
# run the packaged JAR

if [ ! -f ./target/sorting-visualizer.jar ]; then
    echo "Jar not found, please build first (./build) or run ./mvnw package."
    exit 1
fi

java -cp "target/sorting-visualizer.jar:target/dependency/*" io.github.compilerstuck.Control.MainController "$@"
